### ISSUE TITLE
create a new data/csv/trope_vectors_15_9.csv to solve problem with end dot and duplicate tropes

### ISSUE THREAD

**Issue by jcarpio** [jcarpio/tv-tropes-word2vec#34] opened 2020-02-21 14:11 UTC

**Comment by JJ** [comment] 2020-02-21 16:42
Far as I understood it, the problem with that data set is that the movie
title was included to generate it. It had nothing to do with the end dot
and duplicate tropes.

**Comment by JJ** [comment] 2020-02-22 08:32
Also, duplicate of #27

**Closed as completed by JJ** 2020-02-22 08:32 UTC
